### ISSUE TITLE
Problem for package installation

### ISSUE THREAD

**Issue by SebBIC** [FafferMcgee/calcium-analysis#2]
Hello Michael,

I wanted to try your calcium analysis package.
Unfortunately, I'm a beginner on R and I'm not able to install it successfully on RStudio.

After launching the commands:
**library(devtools)
install_github("FafferMcgee/calcium-analysis")**

I obtain the following message:

**Error : Failed to install 'CalciumAnalysis' from GitHub:
  installation of package ‘C:/XX/CalciumAnalysis_0.0.0.9000.tar.gz’ had non-zero exit status**

Do you have an idea on how to solve this issue?

Thank you for your help!

**Comment by Poebelchen** [comment]
Hi Micheal,

same overhere (package for ‘CalciumAnalsysis’ is not available (for R version 4.0.1)), I would very much like to run the package. Is there a chance to update the installation guide and quantification? 

Many thanks!

**Comment by FafferMcgee** [comment]
@SebBIC Apologies, I haven't been keeping an eye on this since I haven't used it in a while. That error means that something went wrong with the installation, but it doesn't reference what the problem is. The error should be higher up in the log. I can't offer more than that as I'm also rather new to R and having packages being used by others! Thank you for your interest. 

@Poebelchen I think that's caused because I hadn't built the package for that version of R yet. I've recently worked on it and it should be useful for R Version 4.0.2. I'll look into what might be restriction the R version so strictly.
